services:
- type: web
  name: ping-pong-deploy
  runtime: docker
  repo: https://github.com/xyse/ping-pong-deploy
  plan: free
  envVars:
  - key: PASSWORD
    sync: false
  - key: USERNAME
    sync: false
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
